# Generated by Django 4.0.3 on 2022-03-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortalApp', '0006_alter_comment_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Категория'),
        ),
    ]
